version: 43.0.9
pageUuid: f0745a12-ca65-11ed-82ff-539530aecbdf
appTemplate:
  queryStatusVisibility: false
  rootScreen: null
  version: 2.116.0
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
