<GlobalFunctions>
  <RESTQuery
    id="query1"
    body="{}"
    query="https://httpbin.org/get"
    queryTimeout="10001"
  >
    <ResourceName>REST-WithoutResource</ResourceName>
  </RESTQuery>
</GlobalFunctions>
